# This file was generated by GoReleaser. DO NOT EDIT.
cask "jkins" do
  version "2.462.3"

  on_macos do
    on_arm do
      sha256 "765abd3d311aeb529ee7d2afdcc97a3f03e8b866e4161a244d750832946e5ba4"
      url "https://github.com/jacobhuemmer/jkins/releases/download/v#{version}/jkins_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c2e3483baccc83ffdf10d9f8cd0112452853ffed14ba98a0d4d956ee961c6e9a"
      url "https://github.com/jacobhuemmer/jkins/releases/download/v#{version}/jkins_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e9072a8c768a95cf4386b3dc39237287cdacee23918869580178a8187b583d33"
      url "https://github.com/jacobhuemmer/jkins/releases/download/v#{version}/jkins_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "89a11cf4fde2eebbfad88ef730f00c1d07cbdc1cb814a6c9d034bbfc8a942ba4"
      url "https://github.com/jacobhuemmer/jkins/releases/download/v#{version}/jkins_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jkins"
  desc "Native Go Jenkins CLI with an encrypted local vault"
  homepage "https://github.com/jacobhuemmer/jkins"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jkins"

  # No zap stanza required
end
