# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dops < Formula
  desc "Developer Operations TUI — browse, parameterize, and execute runbooks from the terminal"
  homepage "https://github.com/rundops/dops"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rundops/dops/releases/download/v0.10.0/dops_0.10.0_darwin_amd64.tar.gz"
      sha256 "cafe2844f85776e813b59864a9109b1d8e42490867a364653d9a94481c057a16"

      define_method(:install) do
        bin.install "dops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rundops/dops/releases/download/v0.10.0/dops_0.10.0_darwin_arm64.tar.gz"
      sha256 "37b9c785baf0f9a40ef9239f23589ab30502d4fcc25786619f6e7d23e83b64c1"

      define_method(:install) do
        bin.install "dops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rundops/dops/releases/download/v0.10.0/dops_0.10.0_linux_amd64.tar.gz"
      sha256 "887cf3b0a5b82cdbbecff2e3b915e27033bf18e4b2bf35b2089f5828af3b6372"
      define_method(:install) do
        bin.install "dops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rundops/dops/releases/download/v0.10.0/dops_0.10.0_linux_arm64.tar.gz"
      sha256 "8665e8690cc838ea94779d099b65439e2a14470df102b67e63892abbedb101da"
      define_method(:install) do
        bin.install "dops"
      end
    end
  end

  test do
    system "#{bin}/dops", "version"
  end
end
