# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M365 < Formula
  desc "Microsoft 365 CLI for one signed-in user"
  homepage "https://github.com/jacobhuemmer/m365"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.1.4/m365_0.1.4_darwin_amd64.tar.gz"
      sha256 "4b7bbee73dc48628ae1ff47cffc7896c0421a36ac9404fcf5231229f319a4e7b"

      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.1.4/m365_0.1.4_darwin_arm64.tar.gz"
      sha256 "70ed84116c3818a3ab59093058c291ad9833fa1c42869def5e62d988921bcacd"

      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.1.4/m365_0.1.4_linux_amd64.tar.gz"
      sha256 "3d73a3eea0c884fd422f326f71fef5a67145235c92e19aa61c919a71aa78d1a7"
      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.1.4/m365_0.1.4_linux_arm64.tar.gz"
      sha256 "3357002f3687a2a882a2c980a1a9330e6a298b2234003bcbc6a84a592f16143b"
      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  head "https://github.com/jacobhuemmer/m365.git", branch: "main"

  test do
    assert_match "m365", shell_output("#{bin}/m365 --help")
    assert_match version.to_s, shell_output("#{bin}/m365 --version")
  end
end
