# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M365 < Formula
  desc "Microsoft 365 CLI for one signed-in user"
  homepage "https://github.com/jacobhuemmer/m365"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.2.1/m365_0.2.1_darwin_amd64.tar.gz"
      sha256 "4d16a93620cef0795c1a42a5585aedfffbbb44f034f0deb534ee8e8bb6299517"

      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.2.1/m365_0.2.1_darwin_arm64.tar.gz"
      sha256 "617da6aa5de76f797299e686a1ad59e5b5cce024d89bd89b0769e916ff33b52e"

      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.2.1/m365_0.2.1_linux_amd64.tar.gz"
      sha256 "a7eac0311dcc9407c157440bac6bad7b47cb5b3e9794e260169b6a7febe5ebe6"
      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.2.1/m365_0.2.1_linux_arm64.tar.gz"
      sha256 "b82b120034fcd730e2d222f368c209e48a5e3e361ba306c1b40471454f8e9691"
      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  head "https://github.com/jacobhuemmer/m365.git", branch: "main"

  test do
    assert_match "m365", shell_output("#{bin}/m365 --help")
    assert_match version.to_s, shell_output("#{bin}/m365 --version")
  end
end
