# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M365 < Formula
  desc "Microsoft 365 CLI for one signed-in user"
  homepage "https://github.com/jacobhuemmer/m365"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.4.0/m365_0.4.0_darwin_amd64.tar.gz"
      sha256 "a461f6f06d5e07a4a64fc81b139cf70e29cda7a129d148d176beef00abd2cf73"

      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.4.0/m365_0.4.0_darwin_arm64.tar.gz"
      sha256 "7c1558b8c7de1850d60658db6f86841b393e4355287b1df4f3b51527b434610d"

      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.4.0/m365_0.4.0_linux_amd64.tar.gz"
      sha256 "e1683a2dc697cabc01ac4c213dee44c1b6af86dc6cfc8c9b5d715b09c2179259"
      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.4.0/m365_0.4.0_linux_arm64.tar.gz"
      sha256 "30363cf484078471328de20ad67ecb9102d1f6f286ec2db17632cb41c8733eed"
      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  head "https://github.com/jacobhuemmer/m365.git", branch: "main"

  test do
    assert_match "m365", shell_output("#{bin}/m365 --help")
    assert_match version.to_s, shell_output("#{bin}/m365 --version")
  end
end
